spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: question-service
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/question/**

        - id: quiz-service
          uri: http://127.0.0.1:8090
          predicates:
            - Path=/quiz/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

server:
  port: 8765
