spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: question-service
          uri: lb://QUESTION-SERVICE
          predicates:
            - Path=/question/**

        - id: quiz-service
          uri: lb://QUIZ-SERVICE
          predicates:
            - Path=/quiz/**

server:
  port: 8765
