spring:
  application:
    name: question-service

#  liquibase:
#    enabled: true
#    change-log: classpath:db.changelog/db.changelog-master.xml

  datasource:
    url: jdbc:postgresql://localhost:5432/question_db?useSSL=false
    username: postgres
    password: Podman56
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
