spring:
  application:
    name: quiz-service

  datasource:
    url: jdbc:postgresql://localhost:5432/quizapp_db?useSSL=false
    username: postgres
    password: Podman56
    driver-class-name: org.postgresql.Driver
    schema: quiz_schema

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8081
